# Generated by Django 3.2.5 on 2021-08-16 11:58

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('ad_file', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='files')),
                ('link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('posted_by', models.CharField(default='Godwin', max_length=30)),
                ('description', tinymce.models.HTMLField()),
                ('post_views', models.IntegerField(default=0)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newwebsite.category')),
            ],
        ),
    ]
