# Generated by Django 3.2.5 on 2021-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
