# Generated by Django 3.2.5 on 2021-08-11 10:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
