# Generated by Django 3.2.5 on 2021-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0003_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
