# Generated by Django 3.2.5 on 2021-08-06 21:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0009_post_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('ads', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ads',
        ),
    ]
