# Generated by Django 3.2.5 on 2021-08-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0010_auto_20210806_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ads',
            new_name='ad_file',
        ),
    ]
