# Generated by Django 3.2.5 on 2021-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwebsite', '0011_rename_ads_ads_ad_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_file',
            field=models.FileField(null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
